"""Put ``hermes`` on the user's PATH via a stable wrapper shim.

The pip / Mission Control install channel installs Hermes into a venv whose
``Scripts``/``bin`` dir is *not* on PATH, so ``hermes`` is undiscoverable in a
normal shell even though the install "succeeded".

Rather than appending the venv dir to PATH directly (which breaks the moment
the venv is rebuilt or the install root moves, and accumulates stale entries
across reinstalls), we write a tiny **wrapper shim** into one stable directory
and put *that* directory on PATH:

  * Windows: ``%LOCALAPPDATA%\\hermes\\bin\\hermes.cmd``
  * POSIX:   ``~/.local/bin/hermes``

The shim also bakes ``HERMES_HOME`` (only when the caller hasn't already set
it), so a manually-run ``hermes`` sees the same state root the launcher/
installer provisioned instead of computing a different default.
"""

from __future__ import annotations

import os
import stat
from dataclasses import dataclass
from pathlib import Path

_IS_WINDOWS = os.name == "nt"


@dataclass
class PathSetupResult:
    shim_path: "str | None" = None
    path_dir: "str | None" = None
    path_registered: bool = False
    note: "str | None" = None


def render_windows_shim(hermes_home: str, hermes_exe: str) -> str:
    """Render the ``hermes.cmd`` wrapper contents (pure — unit-testable)."""
    return (
        "@echo off\r\n"
        "rem Hermes Agent command shim - generated by `hermes postinstall`.\r\n"
        f'if not defined HERMES_HOME set "HERMES_HOME={hermes_home}"\r\n'
        f'"{hermes_exe}" %*\r\n'
    )


def render_posix_shim(hermes_home: str, hermes_exe: str) -> str:
    """Render the POSIX ``hermes`` wrapper contents (pure — unit-testable)."""
    return (
        "#!/bin/sh\n"
        "# Hermes Agent command shim - generated by `hermes postinstall`.\n"
        f'export HERMES_HOME="${{HERMES_HOME:-{hermes_home}}}"\n'
        f'exec "{hermes_exe}" "$@"\n'
    )


def _resolve_hermes_exe() -> "str | None":
    """Absolute path to the ``hermes`` console-script the shim should call."""
    from tools.environments.local import _resolve_hermes_bin_dir

    bin_dir = _resolve_hermes_bin_dir()
    if not bin_dir:
        return None
    name = "hermes.exe" if _IS_WINDOWS else "hermes"
    candidate = os.path.join(bin_dir, name)
    if os.path.isfile(candidate):
        return candidate
    # Fall back to the bare name in the resolved dir even if the isfile probe
    # missed (e.g. a ``.cmd`` console-script variant on Windows).
    if _IS_WINDOWS:
        for variant in ("hermes.exe", "hermes.cmd", "hermes.bat"):
            alt = os.path.join(bin_dir, variant)
            if os.path.isfile(alt):
                return alt
    return candidate


def _path_contains(directory: str) -> bool:
    target = os.path.normcase(directory.rstrip("\\/"))
    for entry in os.environ.get("PATH", "").split(os.pathsep):
        if entry and os.path.normcase(entry.rstrip("\\/")) == target:
            return True
    return False


def register_hermes_command(hermes_home: Path) -> PathSetupResult:
    """Install the ``hermes`` wrapper shim and put its dir on PATH.

    Returns a :class:`PathSetupResult` describing what happened.  Best-effort:
    failures are reported via the result rather than raised, so postinstall
    never aborts on a PATH hiccup.
    """
    result = PathSetupResult()
    hermes_exe = _resolve_hermes_exe()
    if not hermes_exe:
        result.note = "Could not locate the hermes executable; PATH shim skipped."
        return result

    home_str = str(hermes_home)

    if _IS_WINDOWS:
        local_appdata = os.environ.get("LOCALAPPDATA")
        if not local_appdata:
            result.note = "LOCALAPPDATA not set; PATH shim skipped."
            return result
        bin_dir = os.path.join(local_appdata, "hermes", "bin")
        shim = os.path.join(bin_dir, "hermes.cmd")
        try:
            os.makedirs(bin_dir, exist_ok=True)
            with open(shim, "w", encoding="ascii", newline="") as f:
                f.write(render_windows_shim(home_str, hermes_exe))
        except OSError as e:
            result.note = f"Could not write shim: {e}"
            return result
        result.shim_path = shim
        result.path_dir = bin_dir

        from hermes_cli import windows_env
        if _path_contains(bin_dir) or windows_env.add_user_path_entry(bin_dir):
            windows_env.broadcast_environment_change()
            result.path_registered = True
        else:
            result.note = f"Add {bin_dir} to your PATH to run `hermes` directly."
        return result

    # POSIX
    bin_dir = os.path.join(str(Path.home()), ".local", "bin")
    shim = os.path.join(bin_dir, "hermes")
    try:
        os.makedirs(bin_dir, exist_ok=True)
        with open(shim, "w", encoding="utf-8", newline="\n") as f:
            f.write(render_posix_shim(home_str, hermes_exe))
        os.chmod(
            shim,
            stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH,
        )
    except OSError as e:
        result.note = f"Could not write shim: {e}"
        return result
    result.shim_path = shim
    result.path_dir = bin_dir

    if _path_contains(bin_dir):
        result.path_registered = True
    else:
        result.path_registered = False
        result.note = (
            f"Add {bin_dir} to your PATH (e.g. in ~/.profile) to run `hermes` directly."
        )
    return result
